name: code_mk
description: Application immersive pour affirmations et méditation
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  flutter_native_splash: ^2.3.2
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  typed_data: ^1.4.0
  universal_io: ^2.2.2
  uuid: ^4.5.1
  web: ^1.1.1
  xdg_directories: ^1.1.0
  xml: ^6.5.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_screen.png
