name: code_mk
description: Application immersive pour affirmations et méditation
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  flutter_native_splash: ^2.3.2
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_screen.png